/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * RotationPan.java
 *
 * Created on 24-feb-2011, 18:37:38
 */

package org.itver.arm.views.gui;

import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import org.itver.arm.models.elements.Axis;

/**
 *
 * @author pablo
 */
public final class RotationPan extends javax.swing.JPanel
                               implements ChangeListener{

    private Axis axis;

    /** Creates new form RotationPan */
    public RotationPan() {
        initComponents();
        this.addChangeListener(this);
    }

    public RotationPan(Axis axis){
        this();
        this.setAxis(axis);
    }

    @Override
    public void stateChanged(ChangeEvent e) {
        if(e.getSource() == this.slider){
            this.spiner.setValue(this.slider.getValue());
            this.slider.setToolTipText("" + this.slider.getValue());
        }
        else{
            Integer val = (Integer) this.spiner.getValue();
            if(val != null &&
               val >= this.slider.getMinimum() &&
               val <= this.slider.getMaximum())
                this.slider.setValue(val);
            else
                this.spiner.setValue(this.slider.getValue());

        }
    }
    
    @Override
    public void setEnabled(boolean enabled){
        super.setEnabled(enabled);
        this.slider.setEnabled(enabled);
        this.spiner.setEnabled(enabled);
    }

    public void addChangeListener(ChangeListener listener){
        this.spiner.addChangeListener(listener);
        this.slider.addChangeListener(listener);
    }

    public void removeChangeListener(ChangeListener listener){
        this.spiner.removeChangeListener(listener);
        this.slider.removeChangeListener(listener);
    }

    public int getMin(){
        return this.slider.getMinimum();
    }

    public void setMin(int min){
        this.slider.setMinimum(min);
    }

    public int getMax() {
        return this.slider.getMaximum();
    }

    public void setMax(int max){
        this.slider.setMaximum(max);
    }

    public int getValue(){
        return this.slider.getValue();
    }

    public void setValue(int val){
        this.slider.setValue(val);
        this.spiner.setValue(val);
    }

    public Axis getAxis(){
        return this.axis;
    }

    public void setAxis(Axis axis){
        this.axis = axis;
        this.setName(axis.name());
        this.setTitle("<html>Axis <b>" + axis.name() + "</b></html>");
    }

    private void setTitle(String name){
        this.label.setText(name);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        slider = new javax.swing.JSlider();
        spiner = new javax.swing.JSpinner();
        label = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(2147483647, 54));
        setOpaque(false);
        setLayout(new java.awt.BorderLayout());

        slider.setMajorTickSpacing(90);
        slider.setMaximum(360);
        slider.setPaintLabels(true);
        slider.setPaintTicks(true);
        slider.setValue(0);
        add(slider, java.awt.BorderLayout.CENTER);

        spiner.setMinimumSize(new java.awt.Dimension(47, 28));
        spiner.setPreferredSize(new java.awt.Dimension(57, 28));
        this.spiner.setValue(this.slider.getValue());
        add(spiner, java.awt.BorderLayout.EAST);

        label.setFont(new java.awt.Font("Lucida Grande", 0, 10));
        label.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label.setText(org.openide.util.NbBundle.getMessage(RotationPan.class, "RotationPan.label.text")); // NOI18N
        add(label, java.awt.BorderLayout.NORTH);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel label;
    private javax.swing.JSlider slider;
    private javax.swing.JSpinner spiner;
    // End of variables declaration//GEN-END:variables



    

}
