/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * RotationsPan.java
 *
 * Created on 24-feb-2011, 20:01:10
 */

package org.itver.arm.views.gui;

import javax.swing.event.ChangeListener;
import org.itver.arm.models.elements.Axis;

/**
 *
 * @author pablo
 */
public class RotationsPan extends javax.swing.JPanel {
    private RotationPan[] panels = new RotationPan[Axis.values().length];

    /** Creates new form RotationsPan */
    public RotationsPan() {
        initComponents();
        initPanels();
    }

    public void addChangeListener(ChangeListener listener){
        for(int i = 0; i < panels.length; i++)
            panels[i].addChangeListener(listener);
    }

    public void removeChangeListener(ChangeListener listener){
        for(int i = 0; i < panels.length; i++)
            panels[i].removeChangeListener(listener);
    }

    public RotationPan getPanelFromAxis(Axis axis){
        return this.panels[axis.ordinal()];
    }

    private void initPanels(){
        for(int i = 0; i < this.panels.length; i++){
            this.panels[i] = new RotationPan(Axis.values()[i]);
            this.panels[i].setEnabled(false);
            this.add(this.panels[i]);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setOpaque(false);
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
